apiVersion: v1
kind: Secret # Kind je paÄ secret.
metadata:
  name: secret-demo # ime secreta.
type: Opaque
data:
  username: a3ViZWFkbWlu # username enkriptiran z base64. V notepadu je opisano, kako dobimo enkriptirano vrednost.
  password: bXlwYXNzd29yZA== # password enkriptiran z base64. V notepadu je opisano, kako dobimo enkriptirano vrednost.
